modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/reusable-rockets/issues"
[[mods]]
modId = "reusable_rockets"
version = "${mod_version}"
displayName = "Reusable Rockets"
updateJSONURL = "https://update.maxhenkel.de/neoforge/reusable_rockets"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/reusable-rockets"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''Reusable Rockets'''
[[dependencies.reusable_rockets]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.reusable_rockets]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.reusable_rockets]]
modId = "jei"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"